Implement Pet GET Endpoint
PetController: Define endpoints for retrieving single pet and list of pets
PetDTO: Define data transfer object that represent json object
EntityExceptionHandler: Define way how to handle exceptions on entities
PetDoesNotExistException: Custom runtime exception for pet entity
TransformerFailedException: Custom runtime exception for dto->entity, entity->dto transformation
PetRepository: JPA repository
PetService: Implement methods for retrieving pets from db
IPetService: Define interface of methods that need to be implemented in PetService
Transformer: Helper class that transforms entity->dto and dto->entity